<?php

use Drupal\Core\Routing\RouteMatchInterface;

function materialweather_theme($existing, $type, $theme, $path) {
  return array(
    'materialweather' => array(
      'variables' => array('materialweather_detail' => NULL),
    ),
    'materialweather_hourlyforecast' => array(
      'variables' => array('hourlyforecast_detail' => NULL),
    ),
    'materialweather_dailyforecast' => array(
      'variables' => array('dailyforecast_detail' => NULL),
    ),
  );
}
